---
# site info
baseurl: ""
description: >-
  I am a Senior Research Software Engineer at the Centre for Advanced Research
  Computing, University College London.
email: patrickjamesroddy (at) gmail (dot) com
google_measurement: G-V1RQT88SBL
goatcounter_site: paddyroddy
google_verification: 2OJZwc2Br7Pci3YdK1yZ0m7pjHttZ_kfCYreAhW2MdI
remote_theme: pages-themes/hacker
repository: paddyroddy/paddyroddy.github.io
title: Patrick J. Roddy
url: https://paddyroddy.github.io

# social media
github_username: paddyroddy
google_scholar_id: OFigHUwAAAAJ
gravatar_hash: b991f7f475c334cc277869a709445d42
linkedin_username: patrickjamesroddy
strava_user: paddyroddy

# disable redirects.json
redirect_from:
  json: false

# plugins
plugins:
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
